# Generated by Django 4.2.4 on 2025-07-22 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='idle', max_length=50)),
                ('realtymx_username', models.CharField(blank=True, max_length=100, null=True)),
                ('realtymx_password', models.CharField(blank=True, max_length=100, null=True)),
                ('limit', models.IntegerField(default=10)),
                ('total', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agent_data',
            },
        ),
        migrations.CreateModel(
            name='SyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('listings_processed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('paused', 'Paused')], max_length=50)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='agents.agent')),
            ],
        ),
    ]
