# Generated by Django 4.2.4 on 2025-07-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
