# Generated by Django 4.2.4 on 2025-07-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='interval',
            field=models.IntegerField(default=7),
        ),
    ]
