# Generated by Django 4.2.4 on 2025-07-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
