# Generated by Django 4.2.4 on 2023-09-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_property_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
    ]
