# Generated by Django 4.2.4 on 2023-09-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='use_desc',
            field=models.CharField(choices=[('streeteasy', 'streeteasy'), ('template', 'template'), ('costume', 'costume')], default='streeteasy', max_length=20),
        ),
    ]
