# Generated by Django 4.2.4 on 2023-09-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_property_use_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('scraped', 'scraped')], max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='reality_user',
            field=models.JSONField(default=[]),
        ),
    ]
