# Generated by Django 4.2.4 on 2023-09-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_property_status_alter_unit_reality_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='reality_user',
            field=models.JSONField(default=[], null=True),
        ),
    ]
