# Generated by Django 4.2.4 on 2023-09-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_unit_reality_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.JSONField(default={'bathroom': {'furnished': [], 'unfurnished': []}, 'bedroom': {'furnished': [], 'unfurnished': []}, 'golf_room': {'furnished': [], 'unfurnished': []}, 'gym': {'furnished': [], 'unfurnished': []}, 'kitchen': {'furnished': [], 'unfurnished': []}, 'livingroom': {'furnished': [], 'unfurnished': []}, 'lobby': {'furnished': [], 'unfurnished': []}, 'lounge': {'furnished': [], 'unfurnished': []}, 'more': {'furnished': [], 'unfurnished': []}, 'others': {'furnished': [], 'unfurnished': []}, 'pool': {'furnished': [], 'unfurnished': []}, 'roof_deck': {'furnished': [], 'unfurnished': []}}),
        ),
    ]
