# Generated by Django 4.2.4 on 2023-11-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_property_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('scraped', 'scraped')], max_length=20)),
                ('reality_user', models.JSONField(default=[], null=True)),
            ],
        ),
    ]
