# Generated by Django 4.2.4 on 2023-11-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refresh',
            name='refresh_at',
            field=models.CharField(max_length=20),
        ),
    ]
