# Generated by Django 4.2.4 on 2023-11-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_refresh_refresh_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refresh',
            name='refresh_at',
            field=models.DateTimeField(),
        ),
    ]
