# Generated by Django 4.2.4 on 2023-11-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_refresh_refresh_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('property_id', models.JSONField(default=[], null=True)),
                ('single_schedule', models.DateTimeField()),
                ('filters', models.JSONField(default={}, null=True)),
                ('reality_user', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('scraped', 'scraped')], max_length=20)),
            ],
        ),
    ]
