# Generated by Django 4.2.4 on 2023-12-26 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduleunits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10, null=True)),
                ('complete_title', models.CharField(max_length=150, null=True)),
                ('beds', models.CharField(max_length=20)),
                ('baths', models.CharField(max_length=15)),
                ('price', models.CharField(max_length=10)),
                ('listing_id', models.IntegerField(default=None, null=True)),
                ('image_urls', models.TextField(null=True)),
                ('image_paths', models.JSONField(null=True)),
                ('description', models.TextField(null=True)),
                ('amenities', models.JSONField(null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('scraped', 'scraped')], max_length=20)),
                ('reality_user', models.JSONField(default=[], null=True)),
                ('isProcessing', models.IntegerField(default=0)),
                ('convertible', models.IntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.property')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schedule')),
            ],
        ),
    ]
