# Generated by Django 4.2.4 on 2023-12-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_scheduleunits_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleunits',
            name='added_at',
        ),
    ]
