# Generated by Django 4.2.4 on 2024-01-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_scheduleunits_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='interval',
            field=models.CharField(default='', max_length=20),
        ),
    ]
