# Generated by Django 4.2.4 on 2024-01-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_schedule_day_schedule_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
