# Generated by Django 4.2.4 on 2024-03-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_property_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
