# Generated by Django 4.2.4 on 2024-05-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_jobs_delete_job_unit_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='reality_user',
        ),
    ]
