# Generated by Django 4.2.4 on 2024-05-03 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_unit_reality_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='property_urls',
            new_name='urls',
        ),
    ]
