# Generated by Django 4.2.4 on 2024-05-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_unit_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='job_status',
            field=models.CharField(default='resume', max_length=20, null=True),
        ),
    ]
