# Generated by Django 4.2.4 on 2024-05-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_unit_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='url',
            field=models.URLField(),
        ),
    ]
