# Generated by Django 4.2.4 on 2024-05-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_unit_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='isProcessing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit',
            name='job_status',
            field=models.CharField(default='running', max_length=20, null=True),
        ),
    ]
