# Generated by Django 4.2.4 on 2024-05-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_jobs_isprocessing_alter_unit_job_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPropertyBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_status', models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('scraped', 'scraped')], max_length=20, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobs')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.property')),
            ],
        ),
    ]
