# Generated by Django 4.2.4 on 2025-07-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_unit_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_title', models.CharField(max_length=124, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='unit_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='prop_type',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='web_title',
            field=models.CharField(choices=[('streeteasy', 'streeteasy'), ('template', 'template'), ('costume', 'costume')], default='template', max_length=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='use_desc',
            field=models.CharField(choices=[('streeteasy', 'streeteasy'), ('template', 'template'), ('costume', 'costume')], default='template', max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='beds',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='property',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='main.property'),
            preserve_default=False,
        ),
    ]
