# Generated by Django 5.1.6 on 2025-08-28 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_unit_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logs', models.JSONField(blank=True, default=list)),
                ('result', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='WebTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_title', models.CharField(max_length=124, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='unit_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='prop_type',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='web_title',
            field=models.CharField(choices=[('streeteasy', 'streeteasy'), ('template', 'template'), ('costume', 'costume')], default='template', max_length=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='use_desc',
            field=models.CharField(choices=[('streeteasy', 'streeteasy'), ('template', 'template'), ('costume', 'costume')], default='template', max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='beds',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.property'),
        ),
    ]
