# Generated by Django 5.1.6 on 2025-08-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_automatedtask_webtitle_jobs_unit_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtask',
            name='account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='ads_per_neighborhood',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='building_cap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='neighborhoods',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='unit_types',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='automatedtask',
            name='logs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='automatedtask',
            name='result',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
