# Generated by Django 5.1.6 on 2025-09-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_automatedtask_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedtask',
            name='logs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
