# Generated by Django 5.1.6 on 2025-09-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_automatedtask_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtask',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
