# Generated by Django 5.1.6 on 2025-09-15 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_webtitle_jobs_unit_ids_property_prop_type_and_more'),
        ('main', '0036_automatedtask_last_result_and_more'),
    ]

    operations = [
    ]
