# Generated by Django 5.1.6 on 2025-09-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_merge_20250916_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtask',
            name='apartment_types',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='schedule_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
