# Generated by Django 5.1.6 on 2025-09-18 12:31

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_automatedtask_apartment_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtask',
            name='no_of_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.JSONField(default=main.models.Property.default_images),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighbour',
            field=models.JSONField(default=main.models.Property.default_neighbour),
        ),
        migrations.AlterField(
            model_name='refresh',
            name='reality_user',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='filters',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='property_id',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleunits',
            name='reality_user',
            field=models.JSONField(default=list, null=True),
        ),
    ]
