# Generated by Django 5.1.6 on 2025-09-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_automatedtask_no_of_runs_alter_property_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtask',
            name='category',
            field=models.CharField(blank=True, default='Open', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='automatedtask',
            name='marketplaces',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
