# Generated by Django 5.1.6 on 2025-09-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_automatedtask_category_automatedtask_marketplaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedtask',
            name='property_status',
            field=models.CharField(blank=True, default='For Sale', max_length=20, null=True),
        ),
    ]
